name: PlanB
main: planb\PlanB
version: 1.3.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Hackers can't cripple your server anymore!
website: https://github.com/NebulaLabs/PocketMine-Plugins/tree/master/PlanB
permissions:
 planb:
  default: true
  children:
   planb.command:
    default: true
    children:
     planb.command.planb:
      default: true
