name: RestartMe
main: restartme\RestartMe
version: 1.3.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Make sure your server stays up all the time!
website: https://github.com/NebulaLabs/PocketMine-Plugins/tree/master/RestartMe
permissions:
 restartme:
  default: op
  children:
   restartme.command:
    default: op
    children:
     restartme.command.restartme:
      default: op
