#Configuration file for GlobalShield v1.1.0
armorChangeNotAllowed: "§cYou're not allowed to change armor!"
breakNotAllowed: "§cYou're not allowed to break blocks!"
chatNotAllowed: "§cYou're not allowed to chat!"
dropNotAllowed: "§cYou're not allowed to drop things!"
eatNotAllowed: "§cYou're not allowed to eat things!"
emptyNotAllowed: "§cYou're not allowed to empty buckets!"
fillNotAllowed: "§cYou're not allowed to fill buckets!"
gamemodeChangeNotAllowed: "§cYou're not allowed to change gamemodes!"
interactionNotAllowed: "§cYou're not allowed to interact with blocks!"
inventoryChangeNotAllowed: "§cYou're not allowed to change your inventory!"
itemNotAllowed: "§cYou're not allowed to use that item!"
placeNotAllowed: "§cYou're not allowed to place blocks!"
levelChangeNotAllowed: "§cYou're not allowed to change levels!"
signChangeNotAllowed: "§cYou're not allowed to edit signs!"
teleportNotAllowed: "§cYou're not allowed to teleport!"